### PR TITLE
Formatting

### PR DESCRIPTION
**Pull request by tsar-boomba**

### CODE REVIEW

**Comment by tsar-boomba** [comment]
plz merge this hang 🥺

**Comment by hmagan** [comment]
> plz merge this hang 🥺

@samperlmutter are we rockin w/ this???  🦖

**Comment by samperlmutter** [comment]
some of those formatting changes are great

**Comment by tsar-boomba** [comment]
not perfect tbh, but way better to have consistent code formatting

**Comment by samperlmutter** [comment]
good point. look into formatting configurations though

**Pull request merged**
